---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AUTOMATED: pwshEmojiExplorer - alarms deployment'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service being deployed. Used for Developer AWS Account Resource Names.

  LambdaS3BucketName:
    Type: String
    Description: The S3 Bucket holding the Lambda code

  LMFunctionS3KeypwshEEUnicodeVersionMonitor:
    Type: String
    Description: S3 Key for the PubXMLMonitor Lambda function(s) zip file

  LMFunctionHandlerpwshEEUnicodeVersionMonitor:
    Type: String
    Description: PubXMLMonitor Lambda HANDLER provided by New-AWSPowerShellLambdaPackage during build

  ResourceType:
    Type: String
    Description: Determine the type of resource that will be deployed
    AllowedValues:
      - core
      - dev
      - test
      - prod

Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-cloudwatchevent.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern
  pwshEEUnicodeVersionMonitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      # Architectures: x86_64
      # AssumeRolePolicyDocument: JSON
      # AutoPublishAlias: String
      # AutoPublishCodeSha256: String
      # CodeSigningConfigArn: String
      CodeUri:
        Bucket: !Ref LambdaS3BucketName
        Key: !Ref LMFunctionS3KeypwshEEUnicodeVersionMonitor
      # DeadLetterQueue: Map | DeadLetterQueue
      # DeploymentPreference: DeploymentPreference
      Description: 'Determines the latest emoji Unicode version release.'
      Environment:
        Variables:
          S3_BUCKET_NAME: !ImportValue pwshEmojiExplorer-PSEEFinalXMLBucket
          SERVICE_NAME: !Ref ServiceName
      # EphemeralStorage: EphemeralStorage
      # EventInvokeConfig: EventInvokeConfiguration
      # Events: EventSource
      # FileSystemConfigs: List
      # FunctionName:
      # FunctionUrlConfig: FunctionUrlConfig
      Handler: !Ref LMFunctionHandlerpwshEEUnicodeVersionMonitor
      # ImageConfig: ImageConfig
      # ImageUri: String
      # InlineCode: String
      # KmsKeyArn: String
      # Layers: List
      MemorySize: 768
      # PackageType: String
      # PermissionsBoundary: String
      Policies:
        - AWSLambdaBasicExecutionRole
        - CloudWatchPutMetricPolicy: {}
        - S3CrudPolicy:
            BucketName: !ImportValue pwshEmojiExplorer-PSEEFinalXMLBucket
        - SSMParameterReadPolicy:
            ParameterName: telegramtoken
        - SSMParameterReadPolicy:
            ParameterName: telegramchannel
      # ProvisionedConcurrencyConfig: ProvisionedConcurrencyConfig
      # ReservedConcurrentExecutions: Integer
      # Role: String
      # RolePath: String
      Runtime: dotnet6
      # RuntimeManagementConfig: RuntimeManagementConfig
      # SnapStart: SnapStart
      Tags:
        ServiceName: !Ref ServiceName
        StackName: !Ref AWS::StackName
        ResourceType: !Ref ResourceType
      Events:
        RateSchedule:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 week)
      Timeout: 60

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
  pwshEEUnicodeVersionMonitorLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: pwshEEUnicodeVersionMonitor
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      # KmsKeyId: String
      LogGroupName: !Sub '/aws/lambda/${pwshEEUnicodeVersionMonitor}'
      RetentionInDays: 14
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: ResourceType
          Value: !Ref ResourceType

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
  # pwshEEUnicodeVersionMonitorAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     ActionsEnabled: true
  #     AlarmActions:
  #       - !ImportValue AlertSNSTopic
  #     AlarmDescription: Alarms if the PubXML file is more than 8 days old.
  #     AlarmName: pwshEEUnicodeVersionMonitor
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     # DatapointsToAlarm: Integer
  #     # EvaluateLowSampleCountPercentile: String
  #     Dimensions:
  #       - Name: PubXML
  #         Value: DaysOld
  #     EvaluationPeriods: 1
  #     # ExtendedStatistic: String
  #     # InsufficientDataActions:
  #     #   - String
  #     MetricName: PubXMLAge
  #     # Metrics:
  #     #   - MetricDataQuery
  #     Namespace: pwshEmojiExplorer
  #     # OKActions:
  #     #   - String
  #     Period: 3600
  #     Statistic: Maximum
  #     Threshold: 8
  #     # ThresholdMetricId: String
  #     TreatMissingData: notBreaching
  #     # Unit: String

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html
  # pwshEEUnicodeVersionMonitorDashboard:
  #   Type: AWS::CloudWatch::Dashboard
  #   Properties:
  #     DashboardName: !Sub '${ServiceName}-pwshEEUnicodeVersionMonitorDashboard'
  #     DashboardBody: !Sub |
  #       {
  #         "widgets": [
  #             {
  #                 "height": 12,
  #                 "width": 7,
  #                 "y": 0,
  #                 "x": 0,
  #                 "type": "metric",
  #                 "properties": {
  #                     "metrics": [
  #                         [
  #                             "pwshEmojiExplorer",
  #                             "PubXMLAge",
  #                             "PubXML",
  #                             "DaysOld",
  #                             {
  #                                 "region": "us-west-2",
  #                                 "label": "Data Cache Age (Days)"
  #                             }
  #                         ]
  #                     ],
  #                     "view": "timeSeries",
  #                     "stacked": false,
  #                     "region": "us-west-2",
  #                     "period": 86400,
  #                     "stat": "Maximum",
  #                     "start": "-P90D",
  #                     "end": "P0D",
  #                     "annotations": {
  #                         "horizontal": [
  #                             {
  #                                 "label": "Cache > 8 Days",
  #                                 "value": 8
  #                             }
  #                         ]
  #                     },
  #                     "yAxis": {
  #                         "left": {
  #                             "label": "Days Old",
  #                             "min": 0
  #                         },
  #                         "right": {
  #                             "label": "Date"
  #                         }
  #                     },
  #                     "title": "pwshEmojiExplorer Data Cache Age Metric"
  #                 }
  #             },
  #             {
  #                 "height": 12,
  #                 "width": 6,
  #                 "y": 0,
  #                 "x": 7,
  #                 "type": "metric",
  #                 "properties": {
  #                     "metrics": [
  #                         [
  #                             "AWS/CloudFront",
  #                             "Requests",
  #                             "Region",
  #                             "Global",
  #                             "DistributionId",
  #                             "E2C5YCYVS84449",
  #                             {
  #                                 "region": "us-east-1"
  #                             }
  #                         ]
  #                     ],
  #                     "view": "timeSeries",
  #                     "stacked": false,
  #                     "region": "us-west-2",
  #                     "period": 86400,
  #                     "stat": "Sum",
  #                     "start": "-P90D",
  #                     "end": "P0D",
  #                     "title": "Data Cache Download Requests",
  #                     "yAxis": {
  #                         "left": {
  #                             "label": "Download Count",
  #                             "min": 0
  #                         }
  #                     }
  #                 }
  #             }
  #         ]
  #       }

Outputs:
  pwshEEUnicodeVersionMonitorARN:
    Description: Arn for PubXMLMonitor Lambda
    Value: !GetAtt pwshEEUnicodeVersionMonitor.Arn
    Export:
      Name: !Sub ${ServiceName}-pwshEEUnicodeVersionMonitorARN

  # pwshEEUnicodeVersionMonitorAlarmARN:
  #   Description: PubXMLMonitorAlarm Alarm ARN
  #   Value: !GetAtt pwshEEUnicodeVersionMonitorAlarm.Arn
  #   Export:
  #     Name: !Sub ${ServiceName}-pwshEEUnicodeVersionMonitorAlarmARN
